### ISSUE TITLE
我在您的文章中看到了CPI-GNN的数据与其论文中有所不同

### ISSUE THREAD

**Issue by lzzorlpx** [CSUBioGroup/BACPI#6]
在Tsubaki et al. (2019)的"Compound–protein interaction prediction with end-to-end learning of neural networks for graphs and sequences"这篇文章中，他们的模型AUC达到0.978。但是在您的文章柱状图中这个值只有0.954，请问这是什么原因？

**Comment by ZhangliLu** [comment]
非常抱歉，之前没看到消息。
因为我们没有直接使用Tsubaki et al. (2019)论文中的数值。为了公平起见，我们重新进行了数据划分，并且保证所有的对比方法都在相同的数据划分下进行实验测试，并且所用的到数据也不完全是一样的（采样的负样本不同），实验值有所差距是正常现象。
